version: '3'
services:
  mylo-mysql:
    image: mysql
    container_name: mylo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: alexwu
      MYSQL_PASSWORD: 860727
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - /var/lib/docker/volumes/mylo/mysql:/var/lib/mysql
    networks:
      - mylo-network

  mylo-eureka-server:
    build: ./mylo-eureka-server
    image: mylo-eureka-server:latest
    container_name: mylo-eureka-server
    ports:
      - "8761:8761"
    networks:
      - mylo-network

  mylo-api-gateway:
    build: ./mylo-api-gateway
    image: mylo-api-gateway:latest
    depends_on:
        - mylo-eureka-server
    container_name: mylo-api-gateway
    ports:
      - "8080:8080"
    networks:
      - mylo-network

  mylo-user-service:
    build: ./mylo-user-service
    image: mylo-user-service:latest
    depends_on:
      mylo-mysql:
        condition: service_healthy
    container_name: mylo-user-service
    ports:
      - "8081:8080"
    networks:
      - mylo-network

  mylo-authentication-service:
    build: ./mylo-authentication-service
    image: mylo-authentication-service:latest
    depends_on:
      mylo-mysql:
        condition: service_healthy
    container_name: mylo-authentication-service
    ports:
      - "8082:8080"
    networks:
      - mylo-network

networks:
  mylo-network:
    driver: bridge