CREATE DATABASE IF NOT EXISTS `users`;
CREATE DATABASE IF NOT EXISTS `authentications`;
GRANT ALL PRIVILEGES ON `users`.* TO 'alexwu'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `authentications`.* TO 'alexwu'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;