pipeline {
    agent any
    stages {
        stage('Print PWD') {
            steps {
                script {
                    def currentDir = pwd()
                    echo "Current working directory is: ${currentDir}"
                }
            }
        }
        stage('Change to the sub directory') {
            steps {
                dir('mylo-eureka-server') {
                    sh 'mvn clean package'
                }
            }
        }
        stage('Build') {
            steps {
                def currentDir = pwd()
                echo "Current working directory is: ${currentDir}"
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker Image'
            }
        }
    }
}