pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh 'mvn -f mylo-eureka-server test'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn -f mylo-eureka-server clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker Image'
            }
        }
    }
}